### ISSUE TITLE
"How to use" section

### ISSUE THREAD

**Issue by alimranahmed** [Anomareh/PHP-Twig.tmbundle#46]
I am a twig user, I was very happy to see this package first time. But after installation I didn't understand how to use this package. Expecting instructions or usages section in the readme file. When I installed first time this package, I was confused about how to use this package actually. I think a readme file will make this package more sensible and more easy to use. Thank you.

**Comment by Anomareh** [comment]
Sorry, I don't really understand the issue. This bundle doesn't do anything out of the ordinary. It provides syntax highlighting for the Twig library as well as a handful of snippets. I think maybe you're looking for more general information in regards to bundle usage which I think would be more appropriately provided by the editor you are using rather than in the README of this bundle.

If I am mistaken, feel free to reopen this issue and elaborate.
