### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by iamdto** [Anomareh/PHP-Twig.tmbundle#47]
Since 3326f2b you dropped the extras from this package. I was a big fan of Erebus Light and even the [standalone repository](https://github.com/Anomareh/Erebus-Light.tmTheme) seems to be gone.

Is there any specific reason?

Can I start a new repository with this theme (according credit to you of course)? Or maybe you can bring back standalone repositories?

**Comment by Anomareh** [comment]
I removed the themes from this repo because it was cumbersome keeping the repos in sync and the standalone repos are no longer available as I've merged them all into a single repo. You can find the theme you're looking for [there](/Anomareh/TextMate-Themes).The Erebus in that repo is the Erebus Light you're looking for. I got rid of the original Erebus theme.

**Comment by iamdto** [comment]
Great, it works. Thanks!

**Comment by Anomareh** [comment]
No problem.
